const gameData={colors:[{word:'Rød',options:['Rød','Blå','Grønn','Gul']},{word:'Blå',options:['Blå','Rød','Grønn','Gul']},{word:'Grønn',options:['Grønn','Blå','Rød','Gul']},{word:'Gul',options:['Gul','Rød','Blå','Grønn']},{word:'Oransje',options:['Oransje','Lilla','Rosa','Brun']},{word:'Lilla',options:['Lilla','Oransje','Rosa','Brun']},{word:'Rosa',options:['Rosa','Lilla','Oransje','Brun']},{word:'Brun',options:['Brun','Oransje','Lilla','Rosa']},{word:'Svart',options:['Svart','Hvit','Grå','Beige']},{word:'Hvit',options:['Hvit','Svart','Grå','Beige']}],animals:[{word:'Hund',options:['Hund','Katt','Fugl','Fisk']},{word:'Katt',options:['Katt','Hund','Fugl','Fisk']},{word:'Fugl',options:['Fugl','Hund','Katt','Fisk']},{word:'Fisk',options:['Fisk','Fugl','Katt','Hund']},{word:'Elefant',options:['Elefant','Sjiraff','Sebra','Løve']},{word:'Sjiraff',options:['Sjiraff','Elefant','Sebra','Løve']},{word:'Sebra',options:['Sebra','Elefant','Sjiraff','Løve']},{word:'Løve',options:['Løve','Sebra','Sjiraff','Elefant']},{word:'Kanin',options:['Kanin','Ekorn','Mus','Hamster']},{word:'Ekorn',options:['Ekorn','Kanin','Mus','Hamster']}]};
const correctAnswers={colors:{'Rød':'Rød','Blå':'Blå','Grønn':'Grønn','Gul':'Gul','Oransje':'Oransje','Lilla':'Lilla','Rosa':'Rosa','Brun':'Brun','Svart':'Svart','Hvit':'Hvit','Grå':'Grå','Beige':'Beige'},animals:{'Hund':'Hund','Katt':'Katt','Fugl':'Fugl','Fisk':'Fisk','Elefant':'Elefant','Sjiraff':'Sjiraff','Sebra':'Sebra','Løve':'Løve','Kanin':'Kanin','Ekorn':'Ekorn'}};
const imageAssetsAnimals={Hund:'img/animals/hund.jpg',Katt:'img/animals/katt.jpg',Fugl:'img/animals/fugl.jpg',Fisk:'img/animals/fisk.jpg',Elefant:'img/animals/elefant.jpg',Sjiraff:'img/animals/sjiraff.jpg',Sebra:'img/animals/sebra.jpg',Løve:'img/animals/løve.jpg',Kanin:'img/animals/kanin.jpg',Ekorn:'img/animals/ekorn.jpg'};
const colorMap={'Rød':'#E53935','Blå':'#1E88E5','Grønn':'#43A047','Gul':'#FDD835','Oransje':'#FB8C00','Lilla':'#8E24AA','Rosa':'#F06292','Brun':'#8D6E63','Svart':'#000000','Hvit':'#FFFFFF','Grå':'#9E9E9E','Beige':'#F5F5DC'};
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s)),clamp=(n,min,max)=>Math.max(min,Math.min(max,n)),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function formatCategoryName(k){return k==='colors'?'🌈 Farger':k==='animals'?'🦁 Dyr':k}
function formatModeName(m){return m==='imageToWord'?'🖼️ Bilde → Ord':'🔤 Ord → Bilde'}
function getStars(t,c){if(t<=60&&c===10)return 3;if(t<=90||c>=8)return 2;return 1}
function saveBest(cat,t,c){const k=`ordmatch_best_${cat}`;const p=JSON.parse(localStorage.getItem(k)||'null');const cur={time:t,correct:c,date:new Date().toISOString()};const better=!p||c>p.correct||(c===p.correct&&t<p.time);if(better)localStorage.setItem(k,JSON.stringify(cur))}
function loadBest(){return Object.keys(gameData).map(k=>{const raw=localStorage.getItem(`ordmatch_best_${k}`);return{category:k,best:raw?JSON.parse(raw):null}})}
function renderBestList(){const list=$('#bestList');list.innerHTML='';loadBest().forEach(({category,best})=>{const li=document.createElement('li');const cat=document.createElement('span');cat.textContent=formatCategoryName(category);const val=document.createElement('span');val.textContent=best?`${best.correct}/10 • ${best.time}s`:'—';li.append(cat,val);list.appendChild(li)})}
const state={category:null,questions:[],index:0,correct:0,startTime:0,inProgress:false,keyboardFocus:0,timerId:null,mode:'wordToImage'};
function buildAnimalThumb(word,forQuestion=false){const d=document.createElement('div');d.className=forQuestion?'thumb-question':'thumb';const img=document.createElement('img');img.alt=`Bilde av: ${word}`;const src=imageAssetsAnimals[word];if(src){img.src=src}else{d.style.background='#ddd';img.alt=`Bilde mangler (${word})`;}d.appendChild(img);return d}
function buildColorTile(word,forQuestion=false){const outer=document.createElement('div');outer.className=forQuestion?'thumb-question':'thumb';const tile=document.createElement('div');tile.className='color-tile';tile.style.background=colorMap[word]||'#ccc';outer.appendChild(tile);return outer}
function showMenu(){$('#menu').hidden=false;$('#game').hidden=true;$('#results').hidden=true;renderBestList()}
function showGame(category){state.category=category;const all=gameData[category]??[];state.questions=shuffle(all).slice(0,10);state.index=0;state.correct=0;state.startTime=Date.now();state.inProgress=true;state.keyboardFocus=0;const sel=document.querySelector('input[name="mode"]:checked');state.mode=sel?sel.value:'wordToImage';$('#menu').hidden=true;$('#results').hidden=true;$('#game').hidden=false;$('#gameTitle').textContent=formatCategoryName(category);$('#modeBadge').textContent=formatModeName(state.mode);$('#timer').textContent='0s';$('#backBtn').setAttribute('aria-disabled','true');$('#backBtn').disabled=true;renderQuestion();startTimer()}
function renderQuestion(){const q=state.questions[state.index];const total=10;const prog=clamp(Math.round((state.index/total)*100),0,100);const qEl=$('#question');qEl.classList.remove('visual');qEl.innerHTML='';if(state.mode==='imageToWord'){qEl.classList.add('visual');const visual=(state.category==='animals')?buildAnimalThumb(q.word,true):buildColorTile(q.word,true);qEl.appendChild(visual);qEl.setAttribute('aria-label','Hvilket ord passer til bildet?')}else{qEl.textContent=q.word;qEl.removeAttribute('aria-label')}$('#progress').style.width=`${prog}%`;document.querySelector('.progress-bar').setAttribute('aria-valuenow',String(state.index));const wrap=$('#options');wrap.innerHTML='';const opts=shuffle(q.options);if(state.mode==='imageToWord'){opts.forEach((opt,i)=>{const btn=document.createElement('button');btn.type='button';btn.className='option option-text';btn.textContent=opt;btn.setAttribute('data-word',opt);btn.setAttribute('aria-label',`Svaralternativ ${i+1}: ${opt}`);btn.addEventListener('click',()=>selectAnswer(btn,opt));btn.addEventListener('keydown',ev=>handleOptionKey(ev,i));wrap.appendChild(btn)})}else{opts.forEach((opt,i)=>{const btn=document.createElement('button');btn.type='button';btn.className='option';btn.setAttribute('data-word',opt);btn.setAttribute('aria-label',`Bildealternativ ${i+1} for ${opt}`);const thumb=(state.category==='animals')?buildAnimalThumb(opt,false):buildColorTile(opt,false);btn.append(thumb);btn.addEventListener('click',()=>selectAnswer(btn,opt));btn.addEventListener('keydown',ev=>handleOptionKey(ev,i));wrap.appendChild(btn)})}const first=wrap.querySelector('.option');if(first)first.focus();state.keyboardFocus=0}
function showResults(){const sec=Math.floor((Date.now()-state.startTime)/1000);const stars=getStars(sec,state.correct);$('#game').hidden=true;$('#results').hidden=false;$('#finalTime').textContent=String(sec);$('#correctAnswers').textContent=String(state.correct);$('#stars').textContent='★'.repeat(stars);state.inProgress=false;stopTimer();$('#backBtn').removeAttribute('aria-disabled');$('#backBtn').disabled=false;saveBest(state.category,sec,state.correct);renderBestList()}
function startTimer(){stopTimer();state.timerId=setInterval(()=>{const s=Math.floor((Date.now()-state.startTime)/1000);$('#timer').textContent=`${s}s`},250)}
function stopTimer(){if(state.timerId){clearInterval(state.timerId);state.timerId=null}}
function selectAnswer(btn,chosen){const options=$$('.option');if(options.every(b=>b.disabled))return;const q=state.questions[state.index];const correct=correctAnswers[state.category][q.word];const ok=chosen===correct;options.forEach(b=>b.disabled=true);btn.classList.add(ok?'correct':'incorrect');options.forEach(b=>{if(b.getAttribute('data-word')===correct)b.classList.add('correct')});if(ok)state.correct++;setTimeout(()=>{state.index++;if(state.index>=10)showResults();else renderQuestion()},1200)}
function handleOptionKey(ev,i){const opts=$$('.option');const max=opts.length-1;switch(ev.key){case'ArrowRight':case'ArrowDown':state.keyboardFocus=clamp(state.keyboardFocus+1,0,max);opts[state.keyboardFocus].focus();ev.preventDefault();break;case'ArrowLeft':case'ArrowUp':state.keyboardFocus=clamp(state.keyboardFocus-1,0,max);opts[state.keyboardFocus].focus();ev.preventDefault();break;case'Enter':case' ':opts[i].click();ev.preventDefault();break;case'1':case'2':case'3':case'4':const idx=Number(ev.key)-1;if(idx>=0&&idx<=max)opts[idx].click();ev.preventDefault();break;default:}};
function bindEvents(){document.querySelectorAll('.btn-category[data-category]').forEach(btn=>{btn.addEventListener('click',()=>{const cat=btn.getAttribute('data-category');showGame(cat)})});$('#backBtn').addEventListener('click',()=>{if(state.inProgress)return;showMenu()});$('#toMenu').addEventListener('click',()=>showMenu())}
bindEvents();showMenu();
